#!/bin/bash

which gdb >/dev/null
if [ $? -eq 0 ]; then
  debugger="gdb"
else
  which lldb > /dev/null
  if [ $? -eq 0 ]; then
    debugger="lldb"
  else
    >&2 echo "Could not find debugger"
    exit 1
  fi
fi

os=$(uname)
if [ $os == "Darwin" ]; then
  coredir="/cores"
else
  coredir="."
fi

ulimit -c unlimited
./regression.pl --debugger $debugger --coredir $coredir $*
