#!/bin/bash

set -e

USAGE="$0 [-r=x] [-b=y] dst_branch"

OPTS=$(getopt r:b:h $*)

if [ $? != 0 ] ; then echo "Failed parsing options." >&2 ; exit 1 ; fi

set -- $OPTS

runs=3
batch=1

for i
do
    case "$i" in
    -h)
      echo "help: $USAGE"
      exit 0
      ;;
    -r)
      runs=$2
      shift 2
      ;;
    -b)
      batch=$2
      shift 2
      ;;
    --)
      shift
      break
      ;;
    esac
done

if [ "$#" -lt 1 ]; then
    echo "illegal number of parameters"
    echo "$USAGE"
    exit 2
fi

jobid=$(uuidgen)


dirty=$(git status --porcelain | perl -ne '/^ M (.*)/&& print "$1, "')
if [ "$dirty" ]
then
  echo "Workspace not clean"
  exit 1
fi

dst_branch=$1
shift

echo "cleaning"
make clean > /dev/null
echo "building"
make pc pc_fre > /dev/null
echo "Running regression tests"
./regression --batch $batch --runs $runs --jobid "$jobid"
echo "Running performance tests"
./perf       --batch $batch --runs $runs --jobid "$jobid"
echo "Performance compared to $dst_branch"
./perf_report $dst_branch HEAD
echo "Coverage report"
./coverage_report.sh
