#ifndef SUB_MOVE_H
#define SUB_MOVE_H

enum SUB_MOVE { 
	SUB_MOVE_DONE, 
	SUB_MOVE_FORWARD_WHOLE, 
	SUB_MOVE_FORWARD_HALF,
	SUB_MOVE_TURN_RIGHT,
	SUB_MOVE_TURN_LEFT,
	SUB_MOVE_TURN_AROUND,
	SUB_MOVE_INTEGRATE_RIGHT,
	SUB_MOVE_INTEGRATE_LEFT
};

#endif
